### ISSUE TITLE
HTML for event details

### ISSUE THREAD

**Issue by differentreality** [ApostolosKalovelo/a-colourful-presentation#12]
I think we need to render HTML for the event details, eg. take a look at this page
https://events.stellarouzi.com/#/talks/topics/GSoC/GSoC2019

**Comment by ApostolosKalovelo** [comment]
looking into it

**Comment by ApostolosKalovelo** [comment]
You can do it by wrapping the data around a parent wrapper element, for example <div> DATA </div>(or a span) and then add more html elements inside!

You could check how the data is rendered in the "scroll" page with the svg, showing an introduction for every sector using italic text as the second line

**Comment by differentreality** [comment]
Works like a charm :tada:  Thanks :relaxed:
