### ISSUE TITLE
Cheatsheet!

### ISSUE THREAD

**Issue by differentreality** [ApostolosKalovelo/a-colourful-presentation#15]
- custom name/title for cheatsheet

- Alignment of title when long
![Screenshot from 2019-12-07 20-36-01](https://user-images.githubusercontent.com/4322737/70379115-58ac4c00-1931-11ea-9aba-fb23ea7a36e0.png)

**Comment by differentreality** [comment]
Ahm same for title of codesnippets

**Comment by ApostolosKalovelo** [comment]
fixed!
